// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Services.ProductAPI.DBContext;

#nullable disable

namespace Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230421101953_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Services.ProductAPI.DBContext.Models.Dto.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("8ff2a7bd-bc1a-4e92-8966-cfe9ee433a83"),
                            CategoryName = "Appetizer",
                            Description = "Test",
                            Name = "Snacks",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = new Guid("2cad8b9d-05e8-4685-a122-0622bdd6a201"),
                            CategoryName = "Appetizer",
                            Description = "Test",
                            Name = "Salad",
                            Price = 10.0
                        },
                        new
                        {
                            ProductId = new Guid("61d46d68-1450-4b5f-968f-54c52cc423c5"),
                            CategoryName = "Dessert",
                            Description = "Test",
                            Name = "Pie",
                            Price = 8.9900000000000002
                        },
                        new
                        {
                            ProductId = new Guid("c19122af-3455-4d23-aa77-f199c573cee4"),
                            CategoryName = "Entree",
                            Description = "Test",
                            Name = "Pasta",
                            Price = 18.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
